

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JAVIER CASTILLO
 */
public class factura extends javax.swing.JFrame{
  

    /**
     * Creates new form factura
     */DefaultTableModel model;
    private int index;
    public factura() {
        initComponents();
        cliente.setEnabled(false);
        ped.setEnabled(false);
        e.setEnabled(false);
        prod.setEnabled(false);
        em.setEnabled(false);
        pree.setEnabled(false);
        dap.setEnabled(false);
        to.setEnabled(false);
        
        Calendar cal = Calendar.getInstance();
        String fecha,hora;
        fecha = cal.get(Calendar.DATE)+"/"+cal.get(Calendar.MONTH)+"/"+cal.get(Calendar.YEAR);
        hora = cal.get(Calendar.HOUR_OF_DAY)+ ":"+cal.get(cal.MINUTE)+":"+cal.get(cal.SECOND);
        this.fecha.setText(fecha);
        this.hora.setText(hora);
        cargar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
*/
    void nuevo(){
         pedido.setText(null);
         can.setText(null);
            to.setText(null);
            prod.setText(null);
            pag.setText(null);
            pedido.requestFocus();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        COMPRA = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ped = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        ddd = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        hora2 = new javax.swing.JLabel();
        can = new javax.swing.JTextField();
        Hola = new javax.swing.JScrollPane();
        ta4 = new javax.swing.JTable();
        hora3 = new javax.swing.JLabel();
        e = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pedido = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        dap = new javax.swing.JTextField();
        hora7 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        hora4 = new javax.swing.JLabel();
        hora6 = new javax.swing.JLabel();
        hora5 = new javax.swing.JLabel();
        pag = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jLabel7.setText("Hora");

        COMPRA.setText("jMenuItem1");
        COMPRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMPRAActionPerformed(evt);
            }
        });
        jPopupMenu2.add(COMPRA);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Elephant", 0, 14), new java.awt.Color(255, 51, 51))); // NOI18N
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jLabel1.setText("Marca:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jLabel2.setText("Cliente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 77, -1, -1));

        jLabel3.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jLabel3.setText("No.Producto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 77, -1, -1));
        jPanel1.add(ped, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 72, 75, -1));

        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        jPanel1.add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 72, 56, -1));

        prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodActionPerformed(evt);
            }
        });
        jPanel1.add(prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 72, 51, -1));

        jLabel4.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jLabel4.setText("Empleado :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        em.setText("Diego Mataz");
        jPanel1.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 80, -1));

        ddd.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        ddd.setText("Fecha :");
        jPanel1.add(ddd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jLabel6.setText("Hora :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        hora.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        hora.setText("00/00/00");
        jPanel1.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        fecha.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        fecha.setText("00:00:00");
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 226, -1, -1));

        hora2.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        hora2.setText("Cantidad:");
        jPanel1.add(hora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canActionPerformed(evt);
            }
        });
        jPanel1.add(can, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 56, -1));

        ta4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Hola.setViewportView(ta4);

        jPanel1.add(Hola, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 750, -1));

        hora3.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        hora3.setText("Existentes:");
        jPanel1.add(hora3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));
        jPanel1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 51, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton-comprar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 310, 80));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3flecha_izquierda-ol-thumb - copia.gif"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 40, 40));

        jLabel5.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        jLabel5.setText("No.Pedido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 29, -1, -1));

        pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoActionPerformed(evt);
            }
        });
        jPanel1.add(pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 24, 47, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_prel_imprimir_excel.gif"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 60, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "INGRESE", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("AR ESSENCE", 1, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(dap, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 118, -1));

        hora7.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        hora7.setText("Dinero A Pagar:");
        jPanel3.add(hora7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));
        jPanel3.add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 118, -1));

        hora4.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        hora4.setText("Total");
        jPanel3.add(hora4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        hora6.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        hora6.setText("Pagar");
        jPanel3.add(hora6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 28));

        hora5.setFont(new java.awt.Font("MS PGothic", 1, 12)); // NOI18N
        hora5.setText("Precio");
        jPanel3.add(hora5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        pag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagActionPerformed(evt);
            }
        });
        jPanel3.add(pag, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 118, -1));
        jPanel3.add(pree, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 118, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 290, 150));

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 480, 150));

        agregar.setText("....");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteActionPerformed

    private void prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodActionPerformed

    private void canActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canActionPerformed
can.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_canActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int cant=0;
int exis=0;
int tota=0;

cant= Integer.parseInt(can.getText());
exis= Integer.parseInt(e.getText());
tota=exis-cant;
if(cant>exis)
{
JOptionPane.showMessageDialog(null, "Esta Cantidad NO ESTA DISPONIBLE");

   
cant= Integer.parseInt(can.getText());
exis= Integer.parseInt(e.getText());
tota=exis-cant;
}else{


//Inicia resta 2
int v=0;
int va=0;
int r=0;

v= Integer.parseInt(can.getText());
va= Integer.parseInt(pree.getText());
r=v*va;
dap.setText(String.valueOf(r));

int valor5=0;
int valor=0;
int rest=0;

valor5= Integer.parseInt(pag.getText());
valor= Integer.parseInt(dap.getText());
rest=valor5-valor;
to.setText(String.valueOf(rest));

 
 
if(r>valor5){
    
    JOptionPane.showMessageDialog(null, "Dinero INSUFICIENTE!!");
    


}else{
e.setText(String.valueOf(tota));    


conectar cc = new conectar();
        Connection cn = cc.conexion();
        
        
        
        String c,nm,cor,domi,se,eda,pa,sql;
            
            c=pedido.getText();
            nm=can.getText();
           
            cor=em.getText();
            eda=dap.getText();
            se=prod.getText();
            pa=pag.getText();
         
            
            sql="INSERT INTO pedido (No_pedido,cantidad,empleado,total,no_producto,ingresar) VALUES (?,?,?,?,?,?)";
        try {
            PreparedStatement p  = cn.prepareStatement(sql);
            p.setString(1, c);
            p.setString(2, nm);
            p.setString(3, cor);
            p.setString(4, eda);
            p.setString(5, se);
             p.setString(6, pa);
          
            int m = p.executeUpdate();

            if (m>0){
            JOptionPane.showMessageDialog(null, "Registro Guardado con Exito");
        // nuevo ();
            
            //  bloquear();
            
            }
            cargar("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error!!!!"+ex);
        }
}
}
       // cargar("");
     //   JOptionPane.showMessageDialog(null,"Usted a realizado la compra");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
Venta v= new Venta();
        v.show();
             this.agregar.setEnabled(true);  
             dispose();
    }//GEN-LAST:event_agregarActionPerformed

    private void COMPRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMPRAActionPerformed
       
    }//GEN-LAST:event_COMPRAActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        productos p = new productos();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoActionPerformed
pedido.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_pedidoActionPerformed

    private void pagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagActionPerformed
pag.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_pagActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try {
           ta4.print(); 
            
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null,"Error de programa", "Error\n",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    void cargar (String valor){
   
        String []titulos = {"No_pedido", "Cantidad","Empleado","Total","No.Producto","Ingreso"};
       String []registros = new String [12];
       
       String sql = "select*from pedido where CONCAT(No_pedido,' ',cantidad,' ',empleado,' ',total,' ',ingresar,' ',no_producto) like '%"+valor+"%'";
       
       model= new DefaultTableModel(null,titulos);
       
          conectar cc = new conectar();
        Connection cn = cc.conexion();
        
        try{
            Statement st = cn.createStatement();
           ResultSet rs = st.executeQuery(sql);
          
    
          while (rs .next()){
                 registros[0]= rs.getString("No_pedido");
              registros[1]= rs.getString("cantidad");            
              registros[2]= rs.getString("empleado");
                registros[3]= rs.getString("total");              
               registros[4]= rs.getString("no_producto"); 
              registros[5]= rs.getString("ingresar");
                model.addRow (registros);
                
            }
        ta4.setModel(model);
        
        }catch (SQLException ex){
      
                  JOptionPane.showMessageDialog(null, "Error!!"+ex);
        }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new factura().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem COMPRA;
    private javax.swing.JScrollPane Hola;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField can;
    public static final javax.swing.JTextField cliente = new javax.swing.JTextField();
    private javax.swing.JTextField dap;
    private javax.swing.JLabel ddd;
    public static javax.swing.JTextField e;
    private javax.swing.JTextField em;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel hora2;
    private javax.swing.JLabel hora3;
    private javax.swing.JLabel hora4;
    private javax.swing.JLabel hora5;
    private javax.swing.JLabel hora6;
    private javax.swing.JLabel hora7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JTextField pag;
    public static javax.swing.JTextField ped;
    private javax.swing.JTextField pedido;
    public static final javax.swing.JTextField pree = new javax.swing.JTextField();
    public static final javax.swing.JTextField prod = new javax.swing.JTextField();
    private javax.swing.JTable ta4;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables

   
}
